### PR TITLE
CSS Variables Implementaion For Light Theme And Dark Theme

### PR DESCRIPTION
**Pull request by Bishal-NITS-2003**
Following are the issues that need to be fixed before the dark theme:
1) The Hero Section in the home page has a background image and hence it's color cannot be changed to dark.
2) For the Collaboration Section on the home page, some pictures have transparent backgrounds and some do not.
3) All the paragraph tags used on the home page have no class defined so it is taking the default color that is black only.
4) The arrow SVG used under Book Recommendations in the Resources Page has no class defined hence color cannot be applied.

### CODE REVIEW

**Comment by Ecell23** [comment]
Good work @Bishal-NITS-2003

**Review by Ecell23 — DISMISSED** [review]
Just confirm once if everything is working fine

**Comment by Ruler45** [comment]
Also, for the issues you addressed no 3 and 4 can be fixed easily. So do it, if you can. Assign some classes or use already existing classes if possible.

**Review by Ruler45 — APPROVED** [review]
Good job

**Pull request merged**
